### ISSUE TITLE
Introduce tail behaviour to conduct logs

### ISSUE THREAD

**Issue by fsat** [typesafehub/conductr-cli#114]
Introduce a switch to enable tail behaviour to conduct logs, i.e. `conduct logs -f`.

The changes will done in the CLI
- Poll ConductR control protocol to query for logs
- CLI will need perform delta between logs that's displayed vs received from the server
- Introduce backoff behaviour to when polling for logs when no changes detected
- Backoff timeout will be capped to 3 seconds (perhaps)

**Comment by edwardcallahan** [comment]
The example default [Kibana search](http://conductr.lightbend.com/docs/1.1.x/ConsolidatedLogging#Customizing-Discover-tab) does nicely provide log tailing in the browser.  The combination of ES lite with `conduct logs -f` will be fantastic, particularly for getting started. However, it should be noted that such functionality is available today and the example search is great for that.

**Comment by markusjura** [comment]
The conduct logs tail functionality could be also used to output the log information of a bundle during `conduct run`. This way the user sees exactly at which state the bundle is during startup.

**Comment by fsat** [comment]
This is already implemented by #428.
