### ISSUE TITLE
getLevelName issue with logging

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#115]
From a customer report:

---

By the way, a minor point I encountered when upgrading:

I discovered that Python 3.4.1 (what I had been using) does not work with the latest ConductR CLI due to (from https://docs.python.org/3.4/library/logging.html#module-logging https://docs.python.org/3.4/library/logging.html#module-logging):

logging.getLevelName(lvl)
...
Changed in version 3.4: In Python versions earlier than 3.4, this function could also be passed a text level, and would return the corresponding numeric value of the level. This undocumented behaviour was considered a mistake, and was removed in Python 3.4, but reinstated in 3.4.2 due to retain backward compatibility.

I switched to Python 3.4.2 and that fixed the problem.

**Comment by fsat** [comment]
Fixed by #116
