### ISSUE TITLE
Events and Logs for ConductR Daemon

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/conductr-cli#121]
As an operator, I would like 'conduct events' and 'conduct logs' to be able to provide events and output for the cluster itself so that I can leverage consolidated logging when investigating ConductR's operation.

**Comment by huntc** [comment]
We may want to consider rate limiting requests and increase the total number of lines from 100 to 1000. This would be from ConductR core's perspective.

We should also query the logs each second, compare the last line and render from the next line. If the line is not present then we should output a message that lines may be missing in the log output itself.

Finally the command should consider the following args:

```
conduct logs —conductr
conduct logs —conductr-core
conduct logs —conductr-agent
```

**Comment by huntc** [comment]
We should also strongly highlight warning and error level items.
