### ISSUE TITLE
Provide start alias for run command

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#127]
A lot of users initially type `conduct start` or `sandbox start` to start a bundle or the sandbox. We should create a `start` alias that does the exact same as the `run` command.

**Comment by huntc** [comment]
Historic reference: we used to have "start" instead of "run". :-)

We should have one or the other.

**Comment by viktorklang** [comment]
What about, "begin" or "commence". Or perhaps "engage"?

On Tue, Mar 22, 2016 at 7:34 PM, Christopher Hunt notifications@github.com
wrote:

> Historic reference: we used to have "start" instead of "run". :-)
> 
> We should have one or the other.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/typesafehub/conductr-cli/issues/127#issuecomment-199953987

## 

Cheers,
√

**Comment by huntc** [comment]
A Trekky after my own heart. :-)

**Comment by huntc** [comment]
Closing - won't fix.
