### ISSUE TITLE
--wait-timeout does not accept any arguments

### ISSUE THREAD

**Issue by JustinPihony** [typesafehub/conductr-cli#129]
Found in [this ticket](https://support.lightbend.com/web/agent/case/6365), conduct ... --wait-timeout ## ignores the ## as it is using a default of store_true.

https://github.com/typesafehub/conductr-cli/blob/master/conductr_cli/conduct_main.py#L106

**Comment by huntc** [comment]
Fixed by https://github.com/typesafehub/conductr-cli/pull/130#issuecomment-201064180

**Comment by huntc** [comment]
Note if you refer to this issue as "Fixes #129" from the associated PR then GitHub will automatically close it. Plus the motivation for the PR becomes apparent given the link. 

Thanks heaps for fixing it.

**Comment by JustinPihony** [comment]
I actually meant to reference it but had a mental hiccup. Thanks for closing!
