### ISSUE TITLE
Support the new Docker for Mac

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#135]
Is not working correctly with the beta version of Docker for Mac. They've changed things again on us it seems. From a customer report, it appears that there is no "default" machine anymore. Using --ip works though.

**Comment by manuelbernhardt** [comment]
I think this one might be a candidate to be reopened. Reporting from Mac OS Sierra with the docker toolbox, which is to say docker-machine.

It appears that somehow the IP of the virtual machine gets resolved to loopback whereas the machine runs on its own IP (returned correctly via docker-machine ip). I don't know that this is in any way related to Sierra though. I think the problem may be in the logic here where it is assumed that if docker ps runs from the terminal, then loopback is a valid IP. In reality though this may not be the case. I would suggest checking first for docker-machine, then for boot2docker and finally default to loopback.
