### ISSUE TITLE
Don't assume VBox is installed

### ISSUE THREAD

**Issue by orefalo** [typesafehub/conductr-cli#138]
Two use cases which break this rule.
1. I use Fusion, no Vbox.
   I start my docker-machine as such. 

```
docker-machine create --vmwarefusion-cpu-count 2 --vmwarefusion-memory-size 2048 --driver vmwarefusion default
```
1. Latest versions on Docker (beta 1.12.0) don't even need the docker-machine anymore.

**Comment by huntc** [comment]
0.30 was released a day or so a go. This should address the points you raise. Closing for now but let me know if there are any issues outstanding. Thanks.
