### ISSUE TITLE
Short ids by default?

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#14]
In order to also encourage the use of short digests, I think it'd be nice to, by default, just output the short form of an digest by default e.g.

``` bash
PROTO  SERVICE          BUNDLE ID                                                          BUNDLE NAME       STATUS
http   9000/visualizer  c1ab77e63b722ef8c6ea8a1c274be053-3cc322b62e7608b5cdf37185240f7853  visualizer-0.1.0  Running
```

could become

``` bash
PROTO  SERVICE          BUNDLE ID        BUNDLE NAME       STATUS
http   9000/visualizer  c1ab77e-3cc322b  visualizer-0.1.0  Running
```

...and have a `--long-digests` option for the current output. WDYT?

**Comment by viktorklang** [comment]
I think that's a good idea—how about enhancing the proposal with:

``` txt
PROTO  SERVICE          BUNDLE SHORT ID  BUNDLE NAME       STATUS
http   9000/visualizer  c1ab77e-3cc322b  visualizer-0.1.0  Running
```

Also, using "digest" for the flag and "id" seems confusing, so perhaps "-l" and "--long-ids"?

**Comment by huntc** [comment]
I don't think highlighting that the id is short is really necessary. Ids can be expressed short or long; they're all ids.

I agree re dropping digest in favour of Id.

Re the short option, we don't use short ids unless they are in common use.

Thanks!
