### ISSUE TITLE
When upgrading to the latest version 0.38, --feature monitoring is broken

### ISSUE THREAD

**Issue by bantonsson** [typesafehub/conductr-cli#168]
When using sandbox port 9200 is not opened and the contrail reporter can't reach elastic search from the outside!

**Comment by bantonsson** [comment]
Works fine with 0.37

**Comment by henrikengstrom** [comment]
I think port `9200` still must be opened when `-f monitoring` is used. It was moved to be opened when `-f logging` is used in 0.38. Please advice @huntc

**Comment by huntc** [comment]
Oh I thought that if the monitoring feature was enable then logging should be enabled - or is that just the bootstrap script in ConductR? Sounds like the CLI also requires similar logic i.e. If monitoring enabled, enable logging. 

Wanna raise a PR on the CLI?

**Comment by pvlugter** [comment]
New monitoring feature included in version 0.39.
