### ISSUE TITLE
Implement restart command for specific bundle.

### ISSUE THREAD

**Issue by ygree** [typesafehub/conductr-cli#174]
Sometimes it's necessary to restart bundles. There are two options to do so right now:
1. scale to zero, the app will be offline for some time
2. login to each node and kill the app, which is very tedious to do

**Comment by huntc** [comment]
Thanks for this. Why is it necessary to restart a bundle though... isn't the actual problem with the bundle such that it requires a restart? :-)

**Comment by huntc** [comment]
Closing due to no response.
