### ISSUE TITLE
Delete bundle configuration file

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#175]
The bundle configuration file should be removed from the `./conductr/cache` directory once it has been loaded to ConductR.

A previous attempt resulted into a permission error on Windows. Therefore, we've disabled the deletion for now.

**Comment by huntc** [comment]
@fsat Did you look at this?

**Comment by markusjura** [comment]
@huntc @fsat Note that when we delete the bundle configuration after a successful load then the offline mode will never be able to use a bundle configuration. The `conductr-haproxy` bundle uses a bundle configuration, i.e. the `sandbox run` command will not work in offline mode if we fix this issue.

Based on this circumstance do we really want to delete the bundle configuration after every successful load? Maybe we should only delete the old bundle configuration files, similar we do that with the bundles: https://github.com/typesafehub/conductr-cli/blob/master/conductr_cli/conduct_load.py#L250

**Comment by huntc** [comment]
I think we want to protect them with perms mostly, and then delete old ones.
