### ISSUE TITLE
Display public-facing port for services declaration

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#194]
In the past we've displayed the public-facing port with `conduct services`:

```
SERVICE       BUNDLE ID  BUNDLE NAME             STATUS
http://:9000  023f9da    reactive-maps-frontend  Running
http://:9999  35af74a    visualizer              Running
```

This is not the case anymore, since we've introduced ACLs. Now the `conduct acls http` command should be used to display the public-facing ports. However, when declaring the `BundleKeys.endpoints` in the `services` and not in the `acl` format, then the ports are not displayed in the `conduct acls http` command:

```
$ conduct acls http
METHOD  PATH  REWRITE  SYSTEM  SYSTEM VERSION  ENDPOINT NAME  BUNDLE ID  BUNDLE NAME  STATUS
```

Tested with the reactive maps bundles that are hosted on bintray:
- reactive-maps-frontend
- reactive-maps-backend-summary
- reactive-maps-backend-region

**Proposal**
The `conduct acls http` command should also list down the public-facing ports declared with the `services` format.

**Comment by huntc** [comment]
The http acls have no idea what port they will be mapped to, hence them not being displayed. The ports are what conductr-haproxy needs them to be.

**Comment by markusjura** [comment]
@huntc So which command should then display the public-facing ports? A user should be able to look up the public-facing ports of services, as it was previously possible with `conduct services`. This is particularly necessary if a user uses ConductR for the first time and want to connect to a service on a particular port.

**Comment by huntc** [comment]
Perhaps some command that outputs haproxy.cfg? conductr-haproxy doesn't even know the ports - it is anything that is in the haproxy.cfg.

We could print the default http port, and any tcp or udp port... but that isn't the whole picture.

**Comment by markusjura** [comment]
Yes, outputting the configuration of the haproxy is the best option here. The logic should be implemented such it can support other proxy solution in the future as well, i.e. if someone uses Nginx then the command should output the Nginx configuration.
