### ISSUE TITLE
Validate empty environment variables

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#196]
If `CONDUCTR_IP` is set but is empty then all `conduct` commands silently fail:

```
$conduct info
<return without any message>
```

The `CONDUCTR_IP` and possible other environment variables used within the conductr-cli should be validated. If they are empty we should return a corresponding error message.

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConductR CLI: ensure CONDUCTR_IP environment is not empty](https://trello.com/c/QbQFAUvf/407-conductr-cli-ensure-conductr-ip-environment-is-not-empty)

**Comment by fsat** [comment]
Fixed with #197
