### ISSUE TITLE
Provide a way to upgrade the cli simpler

### ISSUE THREAD

**Issue by ktoso** [typesafehub/conductr-cli#200]
Other tools solve it via update command in the cli (they also notify that one should upgrade etc):
https://cloud.google.com/sdk/gcloud/reference/components/update 

Why: 
A fixed version of conductr-cli was released, but as user I don't know that it was. I'd have to dig through docs.

Simple version:
`upgrade` / `update` task in `conduct` that'd check if I'm up to date and either download the new version or tell me how to upgrade.

Nice version:
As gcloud, notify me when I use the tool once in a while that I'm using an old version and should upgrade.

**Comment by huntc** [comment]
Do you know of other CLI tools using a similar approach, particularly ones using Python? This could help us explore an implementation. 

I know that the DCOS CLI offers nothing in this regard (also written in Python).

**Comment by huntc** [comment]
This is now resolved due to the CLI being provided as a native image.
