### ISSUE TITLE
Incorrect detection of duplicated services

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#22]
The `services` command is incorrectly reporting duplicate service names:

![image](https://cloud.githubusercontent.com/assets/694893/6162292/5ff2eb9a-b2d4-11e4-916a-2293839ec399.png)

In the above screenshot, the service names for `/cs-desk` and `/visualizer` are reported as being duplicated, but they are not because their service ports are the same. This is entirely permissible. The duplication warning should only appear when the service ports are different for a given service name.

**Comment by 2m** [comment]
Good catch. These are not duplicates but multiple instances of the same bundle.
