### ISSUE TITLE
Waiting for bundle replication before running bundle

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#223]
If the sandbox is started on multiple containers it is possible that feature can not be scaled. This is because the `conduct load` command is waiting that a bundle has been loaded, but it does not wait that the bundle has been replicated to the nodes. A subsequent `conduct run` can fail if it hits a node where the bundle has not been replicated yet.

**Sample output**
```
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.bintray/.credentials
Retrieving file:///Users/mj/workspace/conductr-cli/visualizer
Resolving bundle typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.bintray/.credentials
Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/visualizer/v2-7fe30fb02ff5df19b09fa33cfe03c5cfa4eb7fb4ff8d7422b9662074eca8b333/visualizer-v2-7fe30fb02ff5df19b09fa33cfe03c5cfa4eb7fb4ff8d7422b9662074eca8b333.zip
[#################################################] 100%
Loading bundle to ConductR..
[#################################################] 100%
Bundle 7fe30fb02ff5df19b09fa33cfe03c5cf waiting to be installed
Bundle 7fe30fb02ff5df19b09fa33cfe03c5cf installed
Bundle loaded.
Error: 404 Not Found
Error: No bundle found by the specified Bundle ID/name: '7fe30fb02ff5df19b09fa33cfe03c5cf'
```

**Comment by huntc** [comment]
This problem is now occurring quite often for me. I would have thought that if the `run` was sent to the same node as the `load` then all would be well, particularly given that we're waiting on the load event to complete perform moving on to the run.

We need to fix it though as it has become unreliable. Perhaps we should retry at least 3 times or something.

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The new CLI features loading fails regularly - we need to address this.](https://trello.com/c/YC1nnrJV/439-the-new-cli-features-loading-fails-regularly-we-need-to-address-this)

**Comment by fsat** [comment]
I think the proper fix should be getting the number of members which has `replicator` role (should be all of the members, actually) - and then as part of the `conduct load` for the replication count to be equal of the number of these members.

As a side note, I think I saw similar issue cropping up during CD deploy, although very rarely. So I'd imagine I'll need to revisit ConductR Lib to provide similar fix as well.

**Comment by huntc** [comment]
Another possible solution is for ConductR to reply only when it sees that replication is going to occur, or something. If you've seen this in CD, then I'd like to fix it properly.

**Comment by markusjura** [comment]
@fsat Can be close this issue?

**Comment by huntc** [comment]
Yep, this issue was fixed via ConductR itself.
