### ISSUE TITLE
sandbox run does not handle conductr roles in JVM mode

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#247]
The user can specify ConductR roles when starting the sandbox. These roles need to be specified as JVM arguments when starting the ConductR processes. This is done for the ConductR docker image, but not for the ConductR JVM binaries.

ConductR Docker reference: https://github.com/typesafehub/conductr-cli/blob/master/conductr_cli/sandbox_run_docker.py#L82

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConductR CLI: support the use of roles in JVM-based sandbox](https://trello.com/c/h9lhj3g4/471-conductr-cli-support-the-use-of-roles-in-jvm-based-sandbox)

**Comment by fsat** [comment]
Fixed by #253
