### ISSUE TITLE
ConductR CLI with auth configured should default to https

### ISSUE THREAD

**Issue by longmuir** [typesafehub/conductr-cli#250]
From a user experience perspective, it feels redundant to have to configure a ~/.conductr/settings.conf with conductr.auth.enabled = true, and then for every cli command append   --scheme https. For the case where auth is enabled, https should be the default. For the case where it's disabled, http should be the default.

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConductR CLI: ensure scheme defaults to https if authentication is enabled](https://trello.com/c/SduvnR1S/470-conductr-cli-ensure-scheme-defaults-to-https-if-authentication-is-enabled)
