### ISSUE TITLE
Document how to set up custom resolver

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#255]
It is possible to setup a custom resolvers in the `~/.conductr/settings.conf` file. We should add instructions to the README how to use custom resolvers. 

I've tried to set up a custom resolver but was not sure which value I need to put into `settings.conf`:

```
resolvers = [???]
```

**Comment by fsat** [comment]
@markusjura - it's documented on this page http://conductr.lightbend.com/docs/2.0.x/DeployingBundlesOps#implementing-your-own-custom-resolver

**Comment by markusjura** [comment]
@fsat Thanks for the pointer. We can then close this ticket.
