### ISSUE TITLE
Offline resolver can pick bundle configuration as bundle and vice versa

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#285]
The offline resolver resolves a bundle and a bundle configuration from the cache directory based on the last modified file with a specific name prefix. If a bundle and a bundle configuration start with the same name prefix, it is possible that the bundle configuration is picked up as a bundle and vice versa. The offline resolver does not distinguish between bundles and bundle configuration, it just takes the last modified file in the cache directory.

As a result, a conduct load command can fail if a bundle configuration file is used as a bundle. In fact, if a bundle together with configuration is downloaded then the configuration will always have the latest modified timestamp.

A possible solution is to have separate bundle and bundle configuration directories under the cache directory:
- `.conductr/cache/bundle`
- `.conductr/cache/bundle-configuration`

The offline resolver could then easily distinguish between these two file types.

**Comment by markusjura** [comment]
https://trello.com/c/p40JTBRt/508-cli-offline-resolver-can-pick-bundle-configuration-as-bundle-and-vice-versa

**Comment by huntc** [comment]
I think separate dirs makes sense
