### ISSUE TITLE
Handling ConductR startup error

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#292]
The conductr-cli is currently displaying a misleading exception if the ConductR startup failed:

```
$ sandbox run 2.0.0
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/mj/.conductr/images/core
Extracting ConductR agent to /Users/mj/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Starting ConductR agent instance on 192.168.10.1..
Waiting for ConductR to start..............................
Error: Encountered unexpected error.
Error: Reason: UnboundLocalError local variable 'feature_results' referenced before assignment
Error: Further information of the error can be found in the error log file: /Users/mj/.conductr/errors.log
```

ConductR can fail to start if e.g. the `/etc/hosts` file under macOS is not correctly configured. See https://github.com/typesafehub/conductr/issues/1591

If ConductR was not started successfully we should display an understandable error message. We should possibly also check the `/etc/hosts` file to give guidance how to fix the ConductR startup.

**Comment by huntc** [comment]
See also https://github.com/typesafehub/conductr-cli/issues/290

**Comment by markusjura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [conductr-cli: Handling ConductR startup error](https://trello.com/c/GQCxbXRx/577-conductr-cli-handling-conductr-startup-error)

**Comment by markusjura** [comment]
Fixed by https://github.com/typesafehub/conductr-cli/pull/357
