### ISSUE TITLE
No data when starting sandbox with monitoring

### ISSUE THREAD

**Issue by tommpy** [typesafehub/conductr-cli#301]
To repro:

```
sandbox run 2.0.0 -n 3 --feature visualisation --feature monitoring
conduct load reactive-maps-frontend
conduct load reactive-maps-backend-region
conduct load reactive-maps-backend-summary

conduct run —scale 3 reactive-maps-frontend
conduct run —scale 3 reactive-maps-backend-region
conduct run —scale 3 reactive-maps-backend-summary

go to 192.168.10.1:9008/services/grafana
```

The bashboards are created in grafana, but there are no metrics.  When I open kibana, it asks me to "Configure an index pattern".

I would expect the metrics pipeline to be

**Comment by markusjura** [comment]
@tommpy This is as expected. Please follow these instructions to setup Kibana: http://conductr.lightbend.com/docs/2.0.x/ConsolidatedLogging#Setting-up-Kibana
