### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by manishneo** [typesafehub/conductr-cli#324]
I am using the lagom example chirp example

here are the commands which I execute to run it on conductr

`Activator`

`> sandbox run 2.0.0 -n 3 --feature visualization

- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback  -    
-   classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12 -
- 1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

- |------------------------------------------------|
- | Stopping HAProxy                               |
- |------------------------------------------------|
- sandbox-haproxy
- HAProxy has been successfully stopped
- |------------------------------------------------|
- | Stopping ConductR                              |
- |------------------------------------------------|
- ConductR core pid 11310 stopped
- ConductR agent pid 11311 stopped
- ConductR has been successfully stopped
- |------------------------------------------------|
- | Starting ConductR                              |
- |------------------------------------------------|
- Extracting ConductR core to /Users/admin/.conductr/images/core
- Extracting ConductR agent to /Users/admin/.conductr/images/agent
- Starting ConductR core instance on 192.168.10.1..
- Starting ConductR agent instance on 192.168.10.1..
- Starting ConductR agent instance on 192.168.10.2..
- Starting ConductR agent instance on 192.168.10.3..
- |------------------------------------------------|
- | Starting HAProxy                               |
- |------------------------------------------------|
- Exposing the following ports [80, 443, 3000, 5601, 9000, 9200, 9999]
- 652deb25b3be8304fd5f4bd163387b40bfc9f42cb829ba2054f34a0a7c1e4d28
- Deploying bundle conductr-haproxy with configuration conductr-haproxy-dev-mode
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/conductr-haproxy
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving file:///Users/admin/svn/lagom-java-chirper/conductr-haproxy
- Resolving bundle typesafe/bundle/conductr-haproxy
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/conductr-haproxy/v2-bdfa43d7ade7456af30a95e9ef4bce863d3029dc58b6824f5783881297d1983b/conductr-haproxy-v2-bdfa43d7ade7456af30a95e9ef4bce863d3029dc58b6824f5783881297d1983b.zip
 

- Retrieving configuration..
- Loading bundle configuration from cache typesafe/bundle-configuration/conductr-haproxy-dev-mode
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving file:///Users/admin/svn/lagom-java-chirper/conductr-haproxy-dev-mode
- Resolving bundle configuration typesafe/bundle-configuration/conductr-haproxy-dev-mode
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving https://dl.bintray.com/typesafe/bundle-configuration/typesafe/conductr-haproxy-dev-mode/v2-e5f35046d59c27f4cfeebcc026f3e3b76e027b15223a8961b59d728e559402e2/conductr-haproxy-dev-mode-v2-e5f35046d59c27f4cfeebcc026f3e3b76e027b15223a8961b59d728e559402e2.zip
- Loading bundle to ConductR..
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 waiting to reach expected scale 1
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 expected scale 1 is met
- |------------------------------------------------|
- | Starting logging feature based on eslite       |
- |------------------------------------------------|
- Deploying bundle eslite..
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/eslite
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving file:///Users/admin/svn/lagom-java-chirper/eslite
- Resolving bundle typesafe/bundle/eslite
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/eslite/v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5/eslite-v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip
- Loading bundle to ConductR..
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 waiting to reach expected scale 1
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 expected scale 1 is met
- |------------------------------------------------|
- | Starting visualization feature                 |
- |------------------------------------------------|
- Deploying bundle visualizer..
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/visualizer
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving file:///Users/admin/svn/lagom-java-chirper/visualizer
- Resolving bundle typesafe/bundle/visualizer
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/visualizer/v2-ed7e37a5e00583073946f7544cf01e359b989bded88f39074bfcde915df5701e/visualizer-v2-ed7e37a5e00583073946f7544cf01e359b989bded88f39074bfcde915df5701e.zip
- Loading bundle to ConductR..
- Bundle ed7e37a5e00583073946f7544cf01e35 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle ed7e37a5e00583073946f7544cf01e35 waiting to reach expected scale 1
- Bundle ed7e37a5e00583073946f7544cf01e35 expected scale 1 is met
- |------------------------------------------------|
- | Summary                                        |
- |------------------------------------------------|
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | ConductR                                       |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- ConductR has been started:
-   core instance on 192.168.10.1
-   agent instances on 192.168.10.1, 192.168.10.2, 192.168.10.3
- ConductR service locator has been started on:
-   192.168.10.1:9008
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Proxy                                          |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- HAProxy has been started
- Your Bundles are by default accessible on:
-   192.168.10.1:9000
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Features                                       |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- The following feature related bundles have been started:
-   visualizer on 192.168.10.1:9999
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Bundles                                        |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- Check latest bundle status with:
-   conduct info
- Current bundle status:
- ID               NAME              #REP  #STR  #RUN
- bdfa43d-e5f3504  conductr-haproxy     1     0     1
- 3349b6b          eslite               1     0     1
- ed7e37a          visualizer           1     0     1
- [success] Total time: 1784 s, completed 23 Feb, 2017 5:51:43 PM`
- 

`install

- > install
- [info] Cassandra bundle configuration has been created: /Users/admin/svn/lagom-java-chirper/target/bundle-configuration/cassandra-configuration-8c3a0cc8c98430c5a96187a0c3722f7001051ad5e915cf04114beb59d244ae58.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/friend-impl/target/scala-2.11/friend-impl_2.11-1.0-SNAPSHOT.pom
- [info] Wrote /Users/admin/svn/lagom-java-chirper/friend-api/target/scala-2.11/friend-api_2.11-1.0-SNAPSHOT.pom
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/friend-impl/target/bundle/friend-impl-v1-0b626d3ae1847d7efce07b8181b168d1f5876408a5e258aa9994163bb756332f.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/publisher-api-impl/target/scala-2.11/publisher-api-impl_2.11-1.0-SNAPSHOT.pom
- [info] Wrote /Users/admin/svn/lagom-java-chirper/publisher-api/target/scala-2.11/publisher-api_2.11-1.0-SNAPSHOT.pom
- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/publisher-api-impl/target/bundle/publisher-api-impl-v1-6ae01ff2a86a02cabd2481684a97a0832d72ee69100cbf5eee759ff988121a99.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/load-test-impl/target/scala-2.11/load-test-impl_2.11-1.0-SNAPSHOT.pom
- [info] Wrote /Users/admin/svn/lagom-java-chirper/load-test-api/target/scala-2.11/load-test-api_2.11-1.0-SNAPSHOT.pom
- [info] Wrote /Users/admin/svn/lagom-java-chirper/chirp-api/target/scala-2.11/chirp-api_2.11-1.0-SNAPSHOT.pom
- [info] Wrote /Users/admin/svn/lagom-java-chirper/activity-stream-api/target/scala-2.11/activity-stream-api_2.11-1.0-SNAPSHOT.pom
- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/load-test-impl/target/bundle/load-test-impl-v1-cd0ef0da61946a20bf32b35f81f7d6f537f8d274d35908b20cfd087881755b08.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/chirp-impl/target/scala-2.11/chirp-impl_2.11-1.0-SNAPSHOT.pom
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/chirp-impl/target/bundle/chirp-impl-v1-5bfa64fe749ce8be2ac98845e217b32c2d06fe2a3a990c08596d84e96f728a4f.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/activity-stream-impl/target/scala-2.11/activity-stream-impl_2.11-1.0-SNAPSHOT.pom
- SLF4J: Class path contains multiple SLF4J bindings.
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: Found binding in [jar:file:/Users/admin/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
- SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
- SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/activity-stream-impl/target/bundle/activity-stream-impl-v1-44aa51534cd63b8154b6862cdd5f3bf949d6dee664c8417b1f34bcbaef31aebb.zip
- [info] Wrote /Users/admin/svn/lagom-java-chirper/front-end/target/scala-2.11/front-end_2.11-1.0-SNAPSHOT.pom
- [info] Bundle has been created: /Users/admin/svn/lagom-java-chirper/front-end/target/bundle/front-end-v1-04861973f91c43dae5d3c31c8ba168bd85954161593fed40e24999766fdc14d5.zip
- [info] Bundle configuration has been created: /Users/admin/svn/lagom-java-chirper/front-end/target/bundle-configuration/default-3865df1eef2bde209504a8bd25d7b601f1e8d20f36bd2754c63b445715da7e60.zip
- Restarting ConductR to ensure a clean state...
- |------------------------------------------------|
- | Stopping HAProxy                               |
- |------------------------------------------------|
- sandbox-haproxy
- HAProxy has been successfully stopped
- |------------------------------------------------|
- | Stopping ConductR                              |
- |------------------------------------------------|
- ConductR core pid 14074 stopped
- ConductR agent pid 14076 stopped
- ConductR agent pid 14081 stopped
- ConductR agent pid 14075 stopped
- ConductR has been successfully stopped
- |------------------------------------------------|
- | Starting ConductR                              |
- |------------------------------------------------|
- Extracting ConductR core to /Users/admin/.conductr/images/core
- Extracting ConductR agent to /Users/admin/.conductr/images/agent
- Starting ConductR core instance on 192.168.10.1..
- Starting ConductR agent instance on 192.168.10.1..
- Starting ConductR agent instance on 192.168.10.2..
- Starting ConductR agent instance on 192.168.10.3..
- |------------------------------------------------|
- | Starting HAProxy                               |
- |------------------------------------------------|
- Exposing the following ports [80, 443, 3000, 5601, 9000, 9200, 9999]
- 511cac6c7cc4d976453a8f0d3cddf57fbafcdc4220245149c267f0f71d6dc80a
- Deploying bundle conductr-haproxy with configuration conductr-haproxy-dev-mode
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/conductr-haproxy
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving from cache /Users/admin/.conductr/cache/bundle/conductr-haproxy-v2-bdfa43d7ade7456af30a95e9ef4bce863d3029dc58b6824f5783881297d1983b.zip
- Retrieving configuration..
- Loading bundle configuration from cache typesafe/bundle-configuration/conductr-haproxy-dev-mode
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving from cache /Users/admin/.conductr/cache/configuration/conductr-haproxy-dev-mode-v2-e5f35046d59c27f4cfeebcc026f3e3b76e027b15223a8961b59d728e559402e2.zip
- Loading bundle to ConductR..
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 waiting to reach expected scale 1
- Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 expected scale 1 is met
- |------------------------------------------------|
- | Starting logging feature based on eslite       |
- |------------------------------------------------|
- Deploying bundle eslite..
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/eslite
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving from cache /Users/admin/.conductr/cache/bundle/eslite-v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip
- Loading bundle to ConductR..
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 waiting to reach expected scale 1
- Bundle 3349b6bfbc09e8d88123fee5b33b2717 expected scale 1 is met
- |------------------------------------------------|
- | Starting visualization feature                 |
- |------------------------------------------------|
- Deploying bundle visualizer..
- Retrieving bundle..
- Loading bundle from cache typesafe/bundle/visualizer
- Bintray credentials loaded from /Users/admin/.lightbend/commercial.credentials
- Retrieving from cache /Users/admin/.conductr/cache/bundle/visualizer-v2-ed7e37a5e00583073946f7544cf01e359b989bded88f39074bfcde915df5701e.zip
- Loading bundle to ConductR..
- Bundle ed7e37a5e00583073946f7544cf01e35 is installed
- Bundle loaded.
- Bundle run request sent.
- Bundle ed7e37a5e00583073946f7544cf01e35 waiting to reach expected scale 1
- Bundle ed7e37a5e00583073946f7544cf01e35 expected scale 1 is met
- |------------------------------------------------|
- | Summary                                        |
- |------------------------------------------------|
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | ConductR                                       |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- ConductR has been started:
-   core instance on 192.168.10.1
-   agent instances on 192.168.10.1, 192.168.10.2, 192.168.10.3
- ConductR service locator has been started on:
-   192.168.10.1:9008
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Proxy                                          |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- HAProxy has been started
- Your Bundles are by default accessible on:
-   192.168.10.1:9000
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Features                                       |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- The following feature related bundles have been started:
-   visualizer on 192.168.10.1:9999
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- | Bundles                                        |
- |- - - - - - - - - - - - - - - - - - - - - - - - |
- Check latest bundle status with:
-   conduct info
- Current bundle status:
- ID               NAME              #REP  #STR  #RUN
- bdfa43d-e5f3504  conductr-haproxy     1     0     1
- 3349b6b          eslite               1     0     1
- ed7e37a          visualizer           1     0     1
- Waiting for ConductR to start.
- Deploying friend-impl...
- Deploying publisher-api-impl...
- Deploying load-test-impl...
- Deploying chirp-impl...
- Deploying activity-stream-impl...
- Deploying front-end...
- Deploying cassandra...
- 
- Your system is deployed. Running "conduct info" to observe the cluster.
- ID               NAME                  #REP  #STR  #RUN
- 44aa515          activity-stream-impl     1     1     0
- ed7e37a          visualizer               1     0     1
- 0486197-3865df1  front-end                1     0     1
- cd0ef0d          load-test-impl           1     1     0
- bdfa43d-e5f3504  conductr-haproxy         1     0     1
- 3349b6b          eslite                   1     0     1
- 0b626d3          friend-impl              1     1     0
- 5bfa64f          chirp-impl               1     1     0
- 84ec550-8c3a0cc  cassandra                1     0     0
- 6ae01ff          publisher-api-impl       1     1     0
- 
- [success] Total time: 111 s, completed 23 Feb, 2017 7:03:07 PM

`

after this when I try to hit any service with url like 192.168.10.1:9000/api/chirps/live

it says page not found?

This is how the descriptor looks like `default Descriptor descriptor() {
   

-  // @formatter:off
-     return named("chirpservice").withCalls(
-         pathCall("/api/chirps/live/:userId", this::addChirp),
-         namedCall("/api/chirps/live", this::getLiveChirps),
-         namedCall("/api/chirps/history", this::getHistoricalChirps)
-       ).withAutoAcl(true);
-     // @formatter:on
-   }

`

Can you let me know how to access these services ?

**Comment by huntc** [comment]
The URL you're contacting is for a websocket.

I ran up chirper locally and all appeared well, although I did have to update the sbt-conductr plugin given that I had the latest ConductR CLI. Here's a PR for that: https://github.com/lagom/activator-lagom-java-chirper/pull/46

Here's a screenshot of using a Chrome based WS plugin:

![screen shot 2017-02-24 at 12 12 44 pm](https://cloud.githubusercontent.com/assets/694893/23286289/db20b054-fa8a-11e6-8cfb-1a41dcf75721.png)
