### ISSUE TITLE
conduct info does not work with released ConductR versions

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#340]
The `conduct info` command is now retrieving the license from ConductR by using the `GET /license` endpoint. This endpoint is not available in the latest ConductR version 2.0.2. As a result, the following error is thrown:

```
$ conduct info
Error: 503 Service Unavailable
Error: Cannot presently locate the visualizer service - has it been started?
```

We need to change the conduct info code so that it supports all ConductR versions. So we should not do the license check for certain ConductR versions. This should be also considered in other areas of the conductr-cli where we call the new license endpoints.

**Comment by markusjura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [conductr-cli: conduct info should work for all ConductR versions](https://trello.com/c/d1NGjzyt/575-conductr-cli-conduct-info-should-work-for-all-conductr-versions)

**Comment by huntc** [comment]
Yes, see https://github.com/typesafehub/sbt-conductr/pull/226#issuecomment-285325973

Tolerating 503 errors within conduct info should be sufficient.
