### ISSUE TITLE
use own bintray credentials

### ISSUE THREAD

**Issue by bayarmunkh** [typesafehub/conductr-cli#346]
any way to use own bintray repository without overwriting `~/.lightbend/commercial.credentials` file?

if there is not, it would be nice if i can do something like `conductr load my-repo/bundle --creds my-bintray.credentials`

**Comment by huntc** [comment]
Not at the moment. It could be useful though. PR? :-)

**Comment by bayarmunkh** [comment]
Yea but need to get familiar with python first though.
