### ISSUE TITLE
Display roles and other data with conduct info

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#351]
We should show the compatibility version and roles in `conduct info` so that users don't have to change the name so much.

`conduct info <bundle>` should display a full form of info in relation to filtering the names and ids.

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CLI: Improve conduct info command](https://trello.com/c/8lHYN0AA/582-cli-improve-conduct-info-command)

**Comment by fsat** [comment]
Resolved by #352 and #354
