### ISSUE TITLE
Make the image tag part of bundle config

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#355]
Given the new `bndl` tool I think we can consider the storing of the image tag as bundle configuration - or even use tags for universal bundles as well. This can then be used alongside bundle ids within the CLI tools such as `conduct info`. Perhaps bundles can also be resolved in ConductR using a tag in addition to the existing bundle id/name resolution we perform.

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Display OCI image tags within "conduct info", perhaps alongside bundle ids.](https://trello.com/c/2FoldG2Y/587-display-oci-image-tags-within-conduct-info-perhaps-alongside-bundle-ids)
