### ISSUE TITLE
Times out when resources unavailable

### ISSUE THREAD

**Issue by bayarmunkh** [typesafehub/conductr-cli#384]
When scaling a bundle fails due to no resources available, `conduct` cli waits forever and times out.

I think appropriate  behavior would be fail fast, then report the error to the user.

**Comment by huntc** [comment]
Thanks for this. Closing given that it is a duplicate of https://github.com/typesafehub/conductr-cli/issues/316

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve "conduct run" exiting](https://trello.com/c/F9oVvq3g/669-improve-conduct-run-exiting)
