### ISSUE TITLE
dcos conduct info throws exception

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#387]
Using `dcos conduct info` results into:

```
$ dcos conduct info
Error: 503 Service Unavailable
Error: Cannot presently locate the visualizer service - has it been started?
```

This is the case if a ConductR version on DC/OS is deployed that does not support the license endpoint yet. We usually handle the `404 Not Found` HTTP response by skipping the license check: https://github.com/typesafehub/conductr-cli/blob/master/conductr_cli/license.py#L136

However, `dcos conduct` is using a different HTTP client that throws a `dcos.errors.DCOSHTTPException` instead of returning the `response.code` 404. This exception is not handled which results in the above output.

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix `dcos conduct info`](https://trello.com/c/KCllR9ez/633-fix-dcos-conduct-info)
