### ISSUE TITLE
Allow overriding bundle.conf from configuration bundle

### ISSUE THREAD

**Issue by 2m** [typesafehub/conductr-cli#39]

**Comment by huntc** [comment]
We now have a means of overriding the bundle.conf. If there's a bundle.conf within the optional configuration then it will be used to overlay the bundle's. Make sense?

Closing this as the functionally you speak of is in ConductR itself.

**Comment by huntc** [comment]
Oh, hang on, I see what you mean. We have to also do the overlaying here as well in order to communicate the multiparty form data fields. Re-opening, and thanks for picking this up.

**Comment by huntc** [comment]
Fixed by #37
