### ISSUE TITLE
Running `sandbox run` a a clean machine displays wrong message

### ISSUE THREAD

**Issue by ignasi35** [typesafehub/conductr-cli#398]
Testing `online-auction-scala`on a clean machine I tried to start the sandbox (no conductr-cli) installed. This is the error I got:

```
[info] Set current project to online-auction-scala (in build file:/Users/ignasi/git/projects/lightbend/samples-lagom/online-auction-scala/)
> sandbox run 2.0.5 
[error] ({.}/*:sandbox) The conductr-cli has not been installed. Follow the instructions on http://conductr.lightbend.com/docs/Vector(1, ., 1, ., 1, x)/CLI to install the CLI.
[error] Total time: 0 s, completed Apr 6, 2017 6:25:25 PM
> 
````
It looks like the formatting is wrong. Also, should I get a link to `1.1.1` docs?

**Comment by fsat** [comment]
@ignasi35 - Thanks for reporting this. I think we need to update the link above to the latest and fix the formatting. We should present the link to http://conductr.lightbend.com/docs/2.0.x/Home since it's the ConductR 2.0.* is the latest one that's currently out there.
