### ISSUE TITLE
Docs to install CLI point to bintray

### ISSUE THREAD

**Issue by ignasi35** [typesafehub/conductr-cli#399]
Docs in http://conductr.lightbend.com/docs/2.0.x/CLI specify:

> The CLI is distributed as a “native” distribution for Windows, OS X and Linux. Lightbend hosts these native images at bintray: https://bintray.com/lightbend/generic/conductr-cli. Download an archive that is suitable for your environment and then place the resultant package in a place accessible from your PATH. For example, on Unix, please copy the contents of archive to your /usr/local/bin folder.

but there seems to be no binary there for downloading.

In bintray I found a link to [website](https://github.com/typesafehub/conductr-cli#command-line-interface-cli-for-lightbend-conductr) and ended up using `homebrew`.

**Comment by fsat** [comment]
@ignasi35 - On https://bintray.com/lightbend/generic/conductr-cli there's a list of versions available,  and if you pick the latest version and look at the "Files" tab, you'll see the zip files for Linux, OSX, and Windows.

I'll include the instructions above in the docs.
