### ISSUE TITLE
Make CLI `run` consistent with sbt-typesafe-conductr (has startBundle)

### ISSUE THREAD

**Issue by ktoso** [typesafehub/conductr-cli#40]
`sbt-typesafe-conductr` uses `startBundle`: https://github.com/sbt/sbt-typesafe-conductr#to-use-sbt-typesafe-conductr-in-your-own-project
This CLI uses `run` to start bundles.

Let's decide on one word for this.

Stop is called `stop` in both, that's fine.

**Comment by huntc** [comment]
Yes, this is baggage. We moved to using "run" a while ago.

**Comment by huntc** [comment]
Closing this in favour of https://github.com/sbt/sbt-typesafe-conductr/issues/50

**Comment by ktoso** [comment]
Sure, let's move over there then
