### ISSUE TITLE
Expired license, wrong URL in refer message

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/conductr-cli#412]
My system had an invalid license for 2.1. Load license fails:
`conduct load-license
Error: Your credentials are no longer valid. Please visit https://www.lightbend.com/account/access-token to renew them.
`
It should reference the getting started page, currently /conductr/developer instead

**Comment by huntc** [comment]
I thought that `https://www.lightbend.com/account/access-token` was actually the correct URL... Why isn't it?

**Comment by edwardcallahan** [comment]
Because I was using offline and confusing myself
