### ISSUE TITLE
Distinct authorities causing spurious warnings on service cmd

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#42]
@edwardcallahan Discovered the following warnings when performing `conduct services` having `http://:8080` and `http://milo.typesafe.com` as endpoint services:

``` bash
ubuntu@10:~$ conduct services
SERVICE                   BUNDLE ID        BUNDLE NAME  STATUS 
http://:8080              d248907          visualizer   Running
http://milo.typesafe.com  353a913-bbb42aa  project-doc  Running

WARNING: Multiple endpoints found for the following services: 
WARNING: Service resolution for these services is undefined.
```

Those warnings shouldn't be appearing here as different authorities are used.

**Comment by hseeberger** [comment]
When exactly should WARNINGS be issued?

**Comment by huntc** [comment]
Think of it in a similar way to /etc/services. If you have the same path but different ports then that should be a warning. Different hosts should be allowed though.

**Comment by hseeberger** [comment]
@2m, I have some trouble analyzing this error: Do you have an idea how the existing code in `conduct_services.py` could print the above warning? What bothers me is that there are no services printed after "... for the following services:". On the other hand the script only prints the warning `if len(duplicate_endpoints) > 0`. So what happened here?

**Comment by hseeberger** [comment]
@huntc, I don't understand: Why should two services with different ports be a warning? Shouldn't it be possible to offer two different endpoints?

**Comment by huntc** [comment]
Two services of the same name...

**Comment by hseeberger** [comment]
But we no longer have service names!

**Comment by huntc** [comment]
The path remains the service name. Nothing has changed.

**Comment by huntc** [comment]
@2m Could I get you to look at this? It'll be an easy one for you. Heiko is away and so it'd be a great help. Thanks!

**Comment by 2m** [comment]
Thanks Heiko. Sorry for silently ignoring. For some reason I am not getting notifications when someone mentions me in github.
