### ISSUE TITLE
Cater for changing principals at lb.com

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#424]
As a user I wish to load a new license to my existing cluster as a new principal at lb.com given that I may be migrating from free to commercial with a different account.

A potential solution here is that `conduct load-license` should always ignore any existing auth token thus causing the prompting of a new one. In addition a `conduct update-license` could be introduced that behaves as `load-license` does today i.e. any existing auth token is used.

**Comment by huntc** [comment]
After a long discussion @fsat and I decided to retain `load-license` and offer a `--force/-f` option in order to override any existing token. The user will be relied upon to use `conduct load-license` to discover this option, and no doubt be guided by us should this use-case occur often. If we do find that the use-case occurs often then I think we'll consider offering more advice for `conduct load-license` where there is an existing token.

**Comment by longshorej** [comment]
`conduct load-license -f` exists.
