### ISSUE TITLE
bndl endpoint ideas

### ISSUE THREAD

**Issue by longshorej** [typesafehub/conductr-cli#441]
I'm working on getting the maven build of chirper to work with ConductR's OCI support. This requires the use of `bndl --endpoint` and I'm glad to report that it works!

That being said, I have a couple ideas to make the `--endpoint` a little more user friendly.

1) Can we have it fail if the user specifies a `--component` flag for a component that doesn't exist (perhaps something like: `Invalid component hello3 (Available components: hello1, hello2)`
2) Can we make `--component` optional if the bundle only has a single component in it? For my usage, I have a bundle with a single component `oci-image`, I'd like to simply run `bndl --endpoint activity-stream --endpoint akka-remote` and, since there's only one component, have the command automatically know I'm referencing it.

WDYT @markusjura ?

**Comment by markusjura** [comment]
> 1. Can we have it fail if the user specifies a --component flag for a component that doesn't exist (perhaps something like: Invalid component hello3 (Available components: hello1, hello2)

Yes, I'll create a PR for that today

> Can we make --component optional if the bundle only has a single component in it? For my usage, I have a bundle with a single component oci-image, I'd like to simply run bndl --endpoint activity-stream --endpoint akka-remote and, since there's only one component, have the command automatically know I'm referencing it.

Yes, I wanted to do that anyway. Will start with that today as well. The user doesn't need to specify the `--component` argument if either only one component in the `bundle.conf` exists or if two components exist and one of the components is the "status" component that contains the check start command.

@longshorej cc
