### ISSUE TITLE
Sandbox: unable to resolve ConductR 2.0.4 images and below

### ISSUE THREAD

**Issue by fsat** [typesafehub/conductr-cli#442]
Sandbox image resolution makes the assumption that ConductR 2.0 has OS native distribution.

This is incorrect. Only ConductR 2.0.5 onwards has OS native distribution, and as such ConductR 2.0.4 downwards must use whatever artefact is left available.

To replicate this error:

```
sandbox run 2.0.4
```

**Comment by huntc** [comment]
The problem actually is that we've not built the OS X packages for 2.0.3 and 2.0.4. 

2.0.0, 2.0.1, 2.0.2 and 2.0.5 are fine. Here's 2.0.2

https://bintray.com/lightbend/commercial-releases/ConductR-Agent-Universal/2.0.2#files

My recommendation is to build the OS X images for 2.0.3 and 2.0.4.

**Comment by huntc** [comment]
@fsat I shall release the 2.0.3 and 2.0.4 packages

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release the 2.0.3 and 2.0.4 ConductR images for OS X as they were forgotten.](https://trello.com/c/8Cob7IEs/656-release-the-2-0-3-and-2-0-4-conductr-images-for-os-x-as-they-were-forgotten)

**Comment by huntc** [comment]
This problem is now resolved. I am now able to download the 2.0.3 and 2.0.4 packages successfully:

```
ChristohersMBP2:conductr huntc$ sandbox run --no-default-features 2.0.3
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Bintray credentials loaded from /Users/huntc/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-2.0.3-Mac_OS_X-x86_64.tgz
[#################################################] 100%
Bintray credentials loaded from /Users/huntc/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-agent-2.0.3-Mac_OS_X-x86_64.tgz
[#################################################] 100%
```

and

```
ChristohersMBP2:conductr huntc$ sandbox run --no-default-features 2.0.4
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Bintray credentials loaded from /Users/huntc/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-2.0.4-Mac_OS_X-x86_64.tgz
[#################################################] 100%
Bintray credentials loaded from /Users/huntc/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/lightbend/commercial-releases/conductr-agent-2.0.4-Mac_OS_X-x86_64.tgz
[#################################################] 100%
```
