### ISSUE TITLE
load-license message not needed?

### ISSUE THREAD

**Issue by dwschultz** [typesafehub/conductr-cli#445]
Encountered this while upgrading conductr cluster from alpha1 to alpha3:
```
conduct load-license -f <<< '...'

An access token is required. Please visit https://www.lightbend.com/account/access-token to
obtain one, and a free license or your commercial one.

Please enter your access token: Loading license into ConductR at 172.31.60.175

Licensed To: 1d1400b6-3e12-45fe-b0cc-15790b5a9b73
Expires In: 364 days (Fri 04 May 2018 01:21AM)
Grants: akka-sbr, cinnamon, conductr

License successfully loaded
```

The initial message is confusing. 
1) I'm loading a new access token so the message is out of place to begin with. 
2) What does " and a free license or your commercial one" mean? Perhaps just omit that?

**Comment by longshorej** [comment]
Thanks for submitting this @dwschultz. I believe the language there refers to the license which is also obtained at lightbend.com, but I agree the wording is awkward.

I've created a PR at #446 that fixes the point you raised for # 1. I'd like to get some feedback from the rest of the team ( @edwardcallahan @fsat @huntc @markusjura ) regarding # 2. I agree that we can probably omit that and I'll update my PR when we reach consensus.
