### ISSUE TITLE
Prompt for the auth token when invalid

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#497]
In the situation where the following occurs:

```
$ conduct load-license 
Error: Your credentials are no longer valid. Please visit https://www.lightbend.com/account/access-token to renew them.
```

... we should perhaps overwrite the credentials from `~/.lightbend/auth-token`. Not doing so prevents a new auth token from being applied. The above scenario should cause a prompt for the new auth token.

**Comment by longshorej** [comment]
`conduct load-license -f` is the solution to this.
