### ISSUE TITLE
shatar to shazar

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#5]
@2m Would you mind renaming shatar to shazar and creating a zip archive instead of a tgz?

**Comment by viktorklang** [comment]
shazar sounds awesome

**Comment by deanwampler** [comment]
shizzum http://www.urbandictionary.com/define.php?term=shizzum is more
street.

On Sun, Jan 18, 2015 at 12:16 PM, Viktor Klang (√) <notifications@github.com

> wrote:
> 
> shazar sounds awesome
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/typesafehub/typesafe-conductr-cli/issues/5#issuecomment-70418820
> .

## 

_Dean Wampler, Ph.D._
Typesafe http://typesafe.com
Author: Programming Scala, 2nd Edition
http://shop.oreilly.com/product/0636920033073.do (O'Reilly)
@deanwampler http://twitter.com/deanwampler

I'm speaking at Strata + Hadoop World | Feb 19-20, 2015
http://strataconf.com/big-data-conference-ca-2015 http://bit.ly/17rCi7S
 #strataconf

I'm speaking at Software Architecture Conference | March 16-19, 2015
http://bit.ly/17rCi7S #OreillySACon

**Comment by hseeberger** [comment]
Addressed in https://github.com/typesafehub/typesafe-conductr-cli/pull/6.
