### ISSUE TITLE
Credentials file can only contain one section

### ISSUE THREAD

**Issue by yuchaoran2011** [typesafehub/conductr-cli#507]
My credentials file are defined as follows:

$ cat .lightbend/commercial.credentials 
realm = Bintray
host = dl.bintray.com
user = [my username]
password = [my password]
realm = Bintray API Realm
host = api.bintray.com
user = [csp user]
password = [csp password]

I took the template from https://github.com/yuchaoran2011/csp-provisioning/blob/master/csp-environment/ansible/roles/install_conductr_cli/templates/commercial.credentials.j2

But when I ran:
`sandbox run 2.1.1 --feature visualization`,
I got the following error:

|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Bintray credentials loaded from /home/ubuntu/.lightbend/commercial.credentials
Error: Unable to fetch ConductR core artifact 2.1.1 from Bintray.
Error: Please specify a valid ConductR version.
Error: The latest version can be found on: https://www.lightbend.com/product/conductr/developer

Removing the last 4 lines of the credentials file solved the problem for me.

**Comment by longshorej** [comment]
Thanks for reporting @yuchaoran2011. I'll discuss this at today's standup in 30m and we'll get a PR out.
