### ISSUE TITLE
How do i Set the env CONDUCTR_SANDBOX_WAIT_RETRIES to increase the wait timeout

### ISSUE THREAD

**Issue by ejiro-precious** [typesafehub/conductr-cli#547]
ConductR sanbox refuse to start after a timeout how do i increase this time out... full log

[ejiro@gigglebrains ~]$ sandbox run 2.1.9 -n 3 --feature visualization#
Invalid features: 'visualization#' (choose from 'proxying', 'visualization', 'logging', 'lite-logging', 'monitoring', 'oci-in-docker', 'continuous-delivery')
[ejiro@gigglebrains ~]$ sandbox run 2.1.9 -n 3 --feature visualization
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /home/ejiro/.conductr/images/core
Extracting ConductR agent to /home/ejiro/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start..............................
Error: ConductR has not been started within 60.0 seconds
Error: Set the env CONDUCTR_SANDBOX_WAIT_RETRIES to increase the wait timeout
Error: For more information check the ConductR log file at: /home/ejiro/.conductr/images/core/logs/conductr.log

**Comment by longshorej** [comment]
You can adjust this via the environment variable `CONDUCTR_SANDBOX_WAIT_RETRIES`, e.g. as follows:

```bash
export CONDUCTR_SANDBOX_WAIT_RETRIES=60

sandbox run 2.1.9 -n 3 --feature visualization
```

That being said, perhaps you're using Java 9? That would cause the sandbox to fail -- you'll need to use Java 8. `/home/ejiro/.conductr/images/core/logs/conductr.log` may provide more detail.

Note that ConductR is EOL, and we recommend using Kubernetes for service orchestration.

**Comment by psriramula** [comment]
thanks @longshorej , faced similar issue and had to switch to the 1.8 JDK.

**Comment by ejiro-precious** [comment]
Thanks @longshorej
