### ISSUE TITLE
Not able to run ConductR cli on windows 10.

### ISSUE THREAD

**Issue by ayonsanyal** [typesafehub/conductr-cli#551]
Hi,
I have downloaded and installed ConductR cli on windows10 machine where docker is also installed. When i am trying to run it by using the command described in the documentaion,i am getting the following error:

**C:\Users\AYON SANYAL>sandbox run 1.2.23 -n 3 --feature visualization
Error: Docker is not installed.
Error: We recommend to use one of following the Docker distributions depending on your OS:
Error: Linux: Docker Engine
Error: MacOS: Docker for Mac
Error: For more information checkout: https://www.docker.com/products/overview**

I am able to see that docker is installed on my machine ,below is the information i got when i gave docker version:
C:\Users\AYON SANYAL>docker version
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:09 2017
OS/Arch: windows/amd64

Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22

:45:38 2017
OS/Arch: linux/amd64
Experimental: true

 No idea why   i am getting the above mentioned error.
Can anyone please help  me ?According to the documentation  ,the cli should run on windows also.

Any help would be appriciated

**Comment by longshorej** [comment]
Hi @ayonsanyal,

The sandbox doesn't run on Windows -- the CLI for Windows is purely for managing a remote Linux cluster.

If you want to give ConductR a try from a Windows-based machine, I recommend using a Linux VM or EC2 installation.
