### ISSUE TITLE
Problem resolving licence issue 

### ISSUE THREAD

**Issue by psriramula** [typesafehub/conductr-cli#553]
When used the client application to load-licence geting a 504 

`Error: 504 Gateway Time-out
Error: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>`

**Comment by psriramula** [comment]
It could be the license service down, when I tried to access it via browser also got a 504

https://www.lightbend.com/product/conductr/license?_ga=2.224932371.865038709.1519038914-1166070902.1461066416

**Comment by longshorej** [comment]
Yes, I think this was a transient error with lightbend.com. I've verified that this is now working. Please reopen if you're still seeing issues.

Also, note that ConductR is EOL and we recommend you look into Kubernetes for service orchestration. Our [Lightbend Orchestration for Kubernetes](https://developer.lightbend.com/docs/lightbend-orchestration-kubernetes/latest/) can help get you started.
