### ISSUE TITLE
A new sandbox command

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#70]
Provide what makes sense of the sbt-conductr-sandbox functionality as a CLI tool supporting the following structure:

```
sandbox [run[-n|--nr-of-containers <nr-of-containers>] [--with-features visualization|logging|monitoring] [image-name] | stop]
```

In addition the CLI should default to using the docker-machine/boot2docker ip if available.

**Comment by fsat** [comment]
So the usage should be:

```
sandbox run -n 3 --with-features visualization logging conductr/conductr
```

which will start 3 container from `conductr/conductr` image, and to stop:

```
sandbox stop
```

**Comment by fsat** [comment]
LGTM

**Comment by markusjura** [comment]
We should also change sbt-condutr-sanbox to use --with-features instead of --withFeatures. Issue: https://github.com/typesafehub/sbt-conductr-sandbox/issues/46

**Comment by huntc** [comment]
> So the usage should be:
> 
>    sandbox run -n 3 --with-features visualization logging conductr/conductr

Yes, but the image `conductr/conductr` is optional as it will default to that.

> We should also change sbt-condutr-sanbox to use --with-features instead of --withFeatures. Issue: typesafehub/sbt-conductr-sandbox#46

Yes, good idea.

**Comment by markusjura** [comment]
Addressed by PR https://github.com/typesafehub/conductr-cli/pull/73.
