### ISSUE TITLE
Shorthand for bundle expressions

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#72]
Support a short-hand expression for referring to bintray releases in a similar vein to Docker. For example:

   conduct load https://bintray.com/artifact/download/typesafe/test-bundle-repo/typesafe/simple-test/v0-2aa7b82c2a8db90712252048857f61f9042a404eee058bfc72832daae2342bb7/simple-test-v0-2aa7b82c2a8db90712252048857f61f9042a404eee058bfc72832daae2342bb7.zip

...should be able to abbreviated to something generic:

```
conduct load typesafe/test-bundle-repo/simple-test:v0-2aa7b82c2a8db90712252048857f61f9042a404eee058bfc72832daae2342bb7
```

...and further:

```
conduct load test-bundle-repo/simple-test
```

The above uses the following convention to address the bundle:

```
address = [ "urn:x-bundle:" ] , [ organization , "/" ] , [ repository , "/" ] , package , [ ":" , "v" , compat-version [ "-" , digest ] ]
```

The CLI shall receive a resolver style of plugin architecture supporting the following behaviours.

If no scheme is provided then `urn:x-bundle:` will be assumed (we should register this with IANA).

If the `organization` is not supplied then a resolver will attempt to resolve it against the organisations it has been configured for (we support the name "typesafe" by default in our supplied resolvers).

If the `repository` is not supplied then a resolver will attempt to resolve it against the repositories it has been configured for (we support the name "bundle" by default in our supplied resolvers).

If the `compat-version` (compatibility version) is not supplied then latest upload is assumed and the resolvers will resolve the latest bundle within the repositories they are associated with, addressing the archive with the latest digest that was uploaded.

So the above load command can be shortened further:

```
conduct load typesafe/test-bundle-repo/simple-test
```

...which would get the latest.  Also:

```
conduct load simple-test
```

...would resolve to typesafe/bundle/simple-test given the default resolvers supplying "typesafe" and "bundle" for organisation and repository names respectively.

The following:

```
conduct load typesafe/test-bundle-repo/simple-test:v0
```

would get the latest uploaded bundle with a compatibility version of "v0".
### Bintray considerations

[sbt-bintray-bundle has been upgraded](https://github.com/sbt/sbt-bintray-bundle/pull/1) to publish metadata regarding the latest version in relation to a compatibility version. A package's attributes are used to record the latest version of a bundle in relation to a key named `latest-v{n}` where `{n}` is the compatibility version. Compatibility versions ascend so the highest `n` value will correspond the latest version of a bundle where no compatibility version is specified.

The following bintray api query can be used to determine if a package exists and also retrieve the bundle attributes (for the typesafe org, test-bundle-repo and simple-test-frontend package):

```
https://api.bintray.com/packages/typesafe/test-bundle-repo/simple-test-frontend
```

The json response will contain a `attribute_names` property. All of the ones starting with `latest-v` relate to the compatibility versions. For example:

```
"attribute_names":["latest-v0"]
```

In order to retrieve the actual version for a `latest-v0` (for example):

```
https://api.bintray.com/packages/typesafe/test-bundle-repo/simple-test-frontend/attributes?names=latest-v0
```

which will return a response:

```
[{"name":"latest-v0","type":"version","values":["v0-93cde225792001fd317083407b06631e2254bf29e2832710cc405be06fff5689"]}]
```

**Comment by markusjura** [comment]
+1

**Comment by edwardcallahan** [comment]
Resolvers for bundles. Like it.

**Comment by huntc** [comment]
@eed3si9n WDYT?

**Comment by markusjura** [comment]
> If the `organization` is not supplied then a resolver will attempt to resolve it against the organisations it has been configured for.
> 
> If the `repository` is not supplied then "bundle" will be substituted as the default.

How can I configure the organization? Is "typesafe" the default organization?

Based on the description above the following commands should be equivalent, considering that "typesafe" is the configured organization. Is that correct?

```
conduct load typesafe/bundle/simple-test
conduct load simple-test
```

**Comment by huntc** [comment]
The orgs will be associated with the resolvers

**Comment by markusjura** [comment]
Additional ideas (after consulting with @huntc):
- The resolvers of an organization can be configured. With this it is possible to add a custom resolver, e.g. my custom AWS S3 account
  - The resolver configuration should be stored in a config file inside `~/.conductr`. The config file would contain the "typesafe" resolver as well. Therefore the file would be always created when `conductr-cli` gets installed
  - The resolvers in the config file are ordered. If two resolvers have been specified and the bundle exists in both resolvers then the first resolver wins. This needs to be documented. So the custom resolver should usually be the first resolver in the config file
- Additionally to the configuration of resolver we could support a configuration of the `repository` as well. If this configuration is set the user doesn't need to specify the `repository` name in the phase of loading the bundle
  - The default `repository` is "bundle". This configuration should be stored inside the `~/.conductr` directory (same or separate file as the resolver config?)

**Example**
Let's say we have declared the following configuration (format will be different).

```
resolver = myCompany
repository = myBundles
```

Then the following shorthands should be equivalent:

```
conduct load myCompany/myBundle/simple-test
conduct load myBundle/simple-test
conduct load simple-test
```

@huntc: Correct?

**Comment by fsat** [comment]
Close given #78 is merged
