### ISSUE TITLE
Run diagnostics on the cluster and repair

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#76]
"As an operator I wish to see the health of the cluster at a glance so that I know whether to look further into any problems that are occurring".

While we have the Visualizer as a GUI, it is not intended as a production-grade tool. There is therefore no UI that permits the health of a cluster to be ascertained quickly.

I propose that a `conduct diagnostics` command be introduced that reports on a) overall health, b) member info (including unreachable etc.) and c) prompts recommending any repairs that can be done (supposing the CRDT state becomes invalid for example). As a consequence a "conduct repair" command could be introduced in order to clean things up.

**Comment by ktoso** [comment]
Sounds like a good first step, thanks for opening this ticket :+1: The ui would be a big task; this is actionable quicker and probably provides building-blocks a [if it comes into existence] ui would need to use. 

// Sorry if I sound too obsessed about that part of it, but sincerely believe it's insanely important.

**Comment by jboner** [comment]
I really like this. :+1:

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xQo2T0bK&#x2F;147-conductr-diagnostic-repair-command"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> ConductR diagnostic&#x2F;repair command</a>
