### ISSUE TITLE
Support for wait for conditions

### ISSUE THREAD

**Issue by fsat** [typesafehub/conductr-cli#88]
A use case for this:
- Consider application `A`, `B`, and `C`
- `A` and `B` can be deployed independently of each other
- `C` is dependent on `A` and `B` to be deployed

The conductr-cli at its present form (v0.21) is able to perform parallel deployment of `A` and `B` (via `conduct run --no-wait`), but it does not have a mechanism where it can wait for both `A` and `B` before `C` can be deployed.

The issue is raised to implement the support for this condition - so possibly a new command need to be introduced, i.e. `conduct wait`

**Comment by huntc** [comment]
Done
