### ISSUE TITLE
Readme format on pypi.python.org

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#95]
The [README.rst](https://github.com/typesafehub/conductr-cli/blob/master/README.rst) is not getting correctly formatted on: https://pypi.python.org/pypi/conductr-cli.

This should be fixed with the next release.

**Comment by huntc** [comment]
@markusjura Was this fixed?

**Comment by markusjura** [comment]
No, https://pypi.python.org/pypi/conductr-cli is still not properly formatted. Headlines, code snippets are not identified as such.

**Comment by markusjura** [comment]
This has been solved in the meantime.
