### ISSUE TITLE
Download progress bar when downloading bundle from bintray

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#96]
Bundles from bintray can not be downloaded. Tested it with conductr-cli v0.22 (latest version) and the bundles:
- reactive-maps-frontend
- reactive-maps-backend-region

The download is not succeeding, waited more than 3 minutes..

**Output**

```
mj@MacBook-Pro-2:~/workspace/conductr-cli$ conduct load reactive-maps-backend-region
Retrieving bundle...
Bintray credentials loaded from /Users/mj/.bintray/.credentials
Loading bundle from cache typesafe/bundle/reactive-maps-backend-region
Retrieving file:///Users/mj/workspace/conductr-cli/reactive-maps-backend-region
Bintray credentials loaded from /Users/mj/.bintray/.credentials
Resolving bundle typesafe/bundle/reactive-maps-backend-region
Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/reactive-maps-backend-region/v1-51bc0b59f26b27bcf71fec6af141243404ba46522c6734d0801d578ff9f02111/reactive-maps-backend-region-v1-51bc0b59f26b27bcf71fec6af141243404ba46522c6734d0801d578ff9f02111.zip
```

**Comment by huntc** [comment]
Have you checked to see whether the download is actually there on bintray?

**Comment by edwardcallahan** [comment]
Working here

``` bash
 $ conduct load reactive-maps-backend-region
Retrieving bundle...
Bintray credentials loaded from /home/edc/.bintray/.credentials
Loading bundle from cache typesafe/bundle/reactive-maps-backend-region
Retrieving file:///home/edc/src/ReactiveMaps/reactive-maps-backend-region
Bintray credentials loaded from /home/edc/.bintray/.credentials
Resolving bundle typesafe/bundle/reactive-maps-backend-region
Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/reactive-maps-backend-region/v1-51bc0b59f26b27bcf71fec6af141243404ba46522c6734d0801d578ff9f02111/reactive-maps-backend-region-v1-51bc0b59f26b27bcf71fec6af141243404ba46522c6734d0801d578ff9f02111.zip
Loading bundle to ConductR...
Bundle 51bc0b59f26b27bcf71fec6af1412434 waiting to be installed
Bundle 51bc0b59f26b27bcf71fec6af1412434 installed
Bundle loaded.
Start bundle with: conduct run --ip Godfather 51bc0b5
```

**Comment by markusjura** [comment]
Tried it again. Now it works. However, the download speed with 400 kbit/s is quite slow. As the result downloading the bundles took more than 3 minutes. If the download takes more than 2 minutes people might think that the download doesn't work and cancel them beforehand. I suggest that we at a download progress bar when downloading bundles from bintray. I'll also contact the bintray support to asked if they can speed up the download.

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Qg2RbhGD&#x2F;177-add-progress-bar-for-cli-downloads"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add progress bar for CLI downloads</a>

**Comment by fsat** [comment]
PR #104 addressed this.
