### ISSUE TITLE
conduct doctor command

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#97]
A `conduct doctor` command should be introduced to help the user solving installation issues. The command could check, report and try to repair the following things:
- Verify docker installation 
- Verify docker-machine (or any other VM machine) installation
- Check if the required version of docker / docker-machine is installed
- Check if docker-machine and docker version are compatible
- Check if the system environment variables for docker are set
- Check for conductr-cli, docker and docker-machine updates
- Check VM configuration and suggest memory and cpu settings
- Perform sanity checks to guarantee that the conduct and sandbox command is working

Additional thoughts about what `conduct doctor` should check or perform are welcome :-) 

The reporting and repairing should be inspired by `brew doctor`.

This functionality should be also added to [sbt-conductr](https://github.com/sbt/sbt-conductr).

**Comment by huntc** [comment]
@fsat, @edwardcallahan and I discussed and instead (or perhaps even complementary) to this, we're going to introduce a `sandbox init` command that will ensure the presence of a `conductr` image (not `default`), if `docker-machine` is being used. Environment vars will also be set up.

The effects of running `sandbox init` are benign if there is no `docker-machine` command available, or there is and the `conductr` image already exists.

**Comment by huntc** [comment]
Dup of #76
